version: "3.8"

services:
    redis:
        image: redis:latest
        container_name: redis_cache
        restart: unless-stopped
        ports:
            - "6379:6379"
        networks:
            - laravel_network

networks:
    laravel_network:
